In [46]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [2]:
data = load_breast_cancer()

In [3]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [4]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
dscr = data['DESCR']

In [6]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [7]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [8]:
data['data'].shape

(569, 30)

In [9]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [10]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [12]:
j = 0
for i in data['feature_names']:
  print(i, data['data'][0][j])
  j+=1

mean radius 17.99
mean texture 10.38
mean perimeter 122.8
mean area 1001.0
mean smoothness 0.1184
mean compactness 0.2776
mean concavity 0.3001
mean concave points 0.1471
mean symmetry 0.2419
mean fractal dimension 0.07871
radius error 1.095
texture error 0.9053
perimeter error 8.589
area error 153.4
smoothness error 0.006399
compactness error 0.04904
concavity error 0.05373
concave points error 0.01587
symmetry error 0.03003
fractal dimension error 0.006193
worst radius 25.38
worst texture 17.33
worst perimeter 184.6
worst area 2019.0
worst smoothness 0.1622
worst compactness 0.6656
worst concavity 0.7119
worst concave points 0.2654
worst symmetry 0.4601
worst fractal dimension 0.1189


In [13]:
j = 0
for i in data['feature_names']:
  print(i, data['data'][568][j])
  j+=1

mean radius 7.76
mean texture 24.54
mean perimeter 47.92
mean area 181.0
mean smoothness 0.05263
mean compactness 0.04362
mean concavity 0.0
mean concave points 0.0
mean symmetry 0.1587
mean fractal dimension 0.05884
radius error 0.3857
texture error 1.428
perimeter error 2.548
area error 19.15
smoothness error 0.007189
compactness error 0.00466
concavity error 0.0
concave points error 0.0
symmetry error 0.02676
fractal dimension error 0.002783
worst radius 9.456
worst texture 30.37
worst perimeter 59.16
worst area 268.6
worst smoothness 0.08996
worst compactness 0.06444
worst concavity 0.0
worst concave points 0.0
worst symmetry 0.2871
worst fractal dimension 0.07039


In [15]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [17]:
data['target_names']  # here 0 indicates cancer and 1 indicate non cancer

array(['malignant', 'benign'], dtype='<U9')

In [18]:
data['data'].shape

(569, 30)

In [19]:
data['target'].shape

(569,)

In [20]:
data['filename']

'/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv'

In [21]:
feature = data['data']

In [36]:
label = data['target']

In [25]:
feature

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [27]:
scale = StandardScaler()
feature = scale.fit_transform(feature)
feature

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [28]:
j = 0
for i in data['feature_names']:
  print(i, feature[0][j])
  j+=1

mean radius 1.097063981469985
mean texture -2.0733350146975855
mean perimeter 1.269933688139939
mean area 0.9843749048031146
mean smoothness 1.568466329243421
mean compactness 3.28351467098683
mean concavity 2.6528739837431687
mean concave points 2.5324752164032422
mean symmetry 2.2175150059646414
mean fractal dimension 2.255746885296271
radius error 2.489733926737622
texture error -0.565265059068463
perimeter error 2.833030865855182
area error 2.4875775569611047
smoothness error -0.21400164666895324
compactness error 1.316861568395947
concavity error 0.7240261580803592
concave points error 0.6608199414286061
symmetry error 1.1487566671861764
fractal dimension error 0.9070830809973358
worst radius 1.8866896251792782
worst texture -1.3592934737640856
worst perimeter 2.3036006236225615
worst area 2.0012374893299207
worst smoothness 1.3076862710715431
worst compactness 2.616665023512605
worst concavity 2.109526346572255
worst concave points 2.29607612756179
worst symmetry 2.75062224412495

In [31]:
print(feature[0])
print(label[0])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
malignant


In [40]:
print(feature[101])
print(data['target_names'][label[101]],label[101])

[-2.0296483  -1.36357954 -1.98450403 -1.45444309  1.46883471 -0.54316805
 -1.11487284 -1.26181958  0.43220368  2.18061387 -0.65352708  0.52824001
 -0.65000451 -0.67114189  1.04971626 -0.81811884 -1.05750068 -1.91344745
  0.73224661  0.11540302 -1.72690052 -0.99940869 -1.69336103 -1.22242284
  1.14110988 -0.85284099 -1.30583065 -1.74506282  0.0505464   0.54718591]
benign 1


In [42]:
df = pd.DataFrame(feature ,columns = data['feature_names'])

In [43]:
df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0     1.097064     -2.073335  ...        2.750622                 1.937015
1     1.829821     -0.353632  ...       -0.243890                 0.281190
2     1.579888      0.456187  ...        1.152255                 0.201391
3    -0.768909      0.253732  ...        6.046041                 4.935010
4     1.750297     -1.151816  ...       -0.868353                -0.397100

[5 rows x 30 columns]

In [45]:
df

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [47]:
#500 Training
X_train = feature[:500]
y_train = label[:500]

#35 Validation
X_val = feature[500:535]
y_val = label[500:535]

#34 Testing
X_test = feature[535:]
y_test = label[535:]

In [48]:
model = Sequential()

model.add(Dense(32, activation = 'relu', input_dim = 30))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile( loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [49]:
model.fit( X_train , y_train, epochs = 10, batch_size = 5, validation_data = (X_val, y_val))

Epoch 1/10
100/100 [==============================] - 1s 5ms/step - loss: 0.2315 - accuracy: 0.9100 - val_loss: 0.0583 - val_accuracy: 0.9714
Epoch 2/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0850 - accuracy: 0.9760 - val_loss: 0.1189 - val_accuracy: 0.9714
Epoch 3/10
100/100 [==============================] - 0s 3ms/step - loss: 0.0625 - accuracy: 0.9800 - val_loss: 0.1053 - val_accuracy: 0.9714
Epoch 4/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0454 - accuracy: 0.9820 - val_loss: 0.0886 - val_accuracy: 0.9714
Epoch 5/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0323 - accuracy: 0.9900 - val_loss: 0.1380 - val_accuracy: 0.9714
Epoch 6/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0324 - accuracy: 0.9920 - val_loss: 0.1017 - val_accuracy: 0.9714
Epoch 7/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0264 - accuracy: 0.9900 - val_loss: 0.1522 - val_accuracy: 0.9429
Epoch 

In [50]:
model.evaluate(X_test , y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.0685 - accuracy: 0.9706


[0.06850384175777435, 0.970588207244873]

In [51]:
model.evaluate(X_val , y_val)

2/2 [==============================] - 0s 6ms/step - loss: 0.2048 - accuracy: 0.9429


[0.20479388535022736, 0.9428571462631226]

In [52]:
for i in range(30):
  sample = X_test[i]
  sample = np.reshape(sample, (1,30))

  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-Malignant")

  if (y_test[i] == 1):
    print("*Banign")
  else:
    print("*Melignant")
  print("-----------")

-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------


In [53]:
t = 0
for i in y_val:
  if (i == 1):
    t += 1

print(t)

26


In [54]:
t = 0
for i in y_test:
  if (i == 1):
    t += 1

print(t)

26


In [55]:
X_test[0] * -.1

array([-0.18241403, -0.03654313, -0.18877867, -0.18575144, -0.05863832,
       -0.13182463, -0.15028386, -0.21481449, -0.11514395,  0.00407717,
       -0.10590431,  0.04114087, -0.0910827 , -0.10438254,  0.08210263,
       -0.00381089, -0.02704381, -0.03915519,  0.01286215,  0.04183096,
       -0.16630405,  0.00321166, -0.15768262, -0.16320758,  0.02441043,
       -0.03768171, -0.08209115, -0.15256103, -0.02851246,  0.04575029])